### ISSUE TITLE
Update to 1.20.5

### ISSUE THREAD

**Issue by BetaKors** [hschwar/AccurateBlockPlacement-Reborn#6]
The game loads and everything, but crashes the moment I put a bow in my hand for some reason.

Here's the crash report:
```
[18:37:20] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: net/minecraft/item/Item.method_19263()Z (loaded from file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/Optimized%20Quilt%201.20.5/.fabric/remappedJars/minecraft-1.20.5-0.15.10/client-intermediary.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@a70df36f) called from class net.minecraft.client.render.GameRenderer (loaded from file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/profiles/Optimized%20Quilt%201.20.5/.fabric/remappedJars/minecraft-1.20.5-0.15.10/client-intermediary.jar by net.fabricmc.loader.impl.launch.knot.KnotClassLoader@a70df36f).
	at MC/net.minecraft.client.render.GameRenderer.handler$zza000$accurateblockplacement$onUpdateTargetedEntityComplete(GameRenderer.java:1805) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.render.GameRenderer.updateCrosshairTarget(GameRenderer.java:639) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1953) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1281) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
```

**Comment by BetaKors** [comment]
actually no, it crashes whenever I hold my pickaxe (maybe it's just when I switch the item I'm holding?)

**Comment by seriousfreezing** [comment]
From what I've tested, it still crashes even if I don't do anything. I minimized my Minecraft and it still crashes.

**Comment by Coobik1234** [comment]
For me, it crashes when I hold my enchanted golden shovel with silk touch.

**Comment by MrErenK** [comment]
> For me, it crashes when I hold my enchanted golden shovel with silk touch.



> For me, it crashes when I hold my enchanted golden shovel with silk touch.

It's probably because of the recent changes in the Minecraft version 1.20.5. I tried to port the mod to 1.20.5/1.20.6 in my [repo](https://github.com/MrErenK/AccurateBlockPlacement-Reborn). You can try that. Warning: this is not the official mod.

**Comment by KadTheHunter** [comment]
Completed in #12.
